var insult_adjectives = ["abortive", "abrasive", "abysmal", "aggressive", "apathetic", "antiquated", "argumentative", "arrogant", "asinine", "backbiting", "bawdy", "beslubbering", "bitter", "bloated", "boastful", "bootlegged", "bossy", "boorish", "brash", "bulbous", "bumpy", "callous", "cantankerous", "careless", "churlish", "clammy", "clingy", "cockered", "corpulent", "creepy", "cruel", "crusty", "cowardly", "dankish", "deceitful", "delirious", "despicable", "detestable", "dim-witted", "dishonest", "disheveled", "disgruntled", "dismal", "dreary", "droning", "dubious", "duplicitous", "edgy", "errant", "evasive", "fanatical", "fatuous", "feeble", "feckless", "flea-ridden", "flimsy", "fobbing", "foul", "fussy", "gelatinous", "gloomy", "glum", "goatish", "greasy", "greedy", "grizzled", "grotesque", "grubby", "grumpy", "hairy", "harsh", "hifalutin", "histrionic", "ignorant", "ill-defined", "impatient", "impulsive", "incapable", "incompetent", "inconsiderate", "inept", "infantile", "irksome", "jealous", "jittery", "knuckle-dragging", "lilly-livered", "limp", "lousy", "lukewarm", "lumpish", "mangled", "miniscule", "miserable", "moody", "mouth-breathing", "mundane", "narrow-minded", "neurotic", "noxious", "objectionable", "obnoxious", "obsessive", "obstinate", "obtuse", "oozing", "overbearing", "overcritical", "patronising", "paunchy", "peckish", "pedantic", "petulant", "pompous", "presumptive", "prickly", "pus-filled", "querulous", "rank", "recalcitrant", "repugnant", "rude", "sarcastic", "scabby", "selfish", "shiftless", "sloppy", "spiteful", "spleeny", "stubborn", "stuffed", "sulky", "sullen", "surly", "swollen", "tactless", "tepid", "thoughtless", "tone deaf", "touchy", "turgid", "truculent", "Trumpish", "unnerving", "uptight", "untrustworthy", "unhappy", "unkempt", "unsightly", "useless", "vapid", "volatile", "walking", "wayward", "weak-willed", "withering", "wretched", "yeasty"]

var insult_expletives_nsfw  = [ "arse", "ass", "bitch", "bollock", "boner", "butthole", "clitoris", "clunge", "cock", "cocknose", "crap", "crotch", "cum", "cunt", "dick", "dildo",  "dong", "ejaculate", "fuck", "gash", "jizz", "motherfucking", "muff", "nutsack", "orgasm", "penis", "piss", "pissflap", "prick", "pube", "pussy", "queef", "rectum", "schlong", "screw", "scrote", "scrotum", "semen", "shag", "shit", "shitdick", "slag", "slit", "slut", "smegma", "smut", "snatch", "taint", "testicle", "tit", "twat", "vag", "vajayjay", "vagina"];

var insult_expletives = ["backdoor", "backside", "ba-donk-a-donk", "bag", "bagpipe", "banana", "bazooka", "beaver", "bits", "boob", "booty", "bottom", "bum", "bush", "butt", "carpet", "cervix", "chubby", "clam", "colon", "coochie", "cooter", "cornhole", "crease", "crotch", "dangle", "derrière", "ding-a-ling", "ding-dong", "dingle", "dink", "dipstick","dongle", "dookie", "douche", "enema", "equipment", "fanny", "fart", "flesh", "foof", "fufu", "giblet", "gob", "groin", "hardware", "hell", "hiney", "hog", "hoo-ha", "hose", "jimmy", "johnson", "knob", "meat", "mound", "noodle", "organ", "patootie", "pecker", "peenie", "pickle", "pizzle", "pole", "poop", "potty", "rod", "rump", "salami", "schlock", "Schwartz", "skank", "skin", "shaft", "sludge", "snapper", "sphincter", "taco", "tuchus", "turd", "tush", "wang", "wedgie", "weenie", "wiener", "willy", "winkle"];

var insult_nouns = ["apparatus", "assistant", "baboon", "baker", "badger", "ballbag", "bandit", "barnacle", "baster", "bellend", "billboard", "blossum", "bomb", "box", "brownie", "bucket", "burger", "burgler", "cabbage", "camel", "cannon", "canoe", "canteen", "catcher", "carcasses", "clod", "clot", "clotpole", "clown", "codpiece", "crumpet", "cucumber", "deputy", "disaster", "donut", "donkey", "dumpster", "dumpling", "engineer", "exhibitor", "face", "factory", "farmer", "finger", "flunky", "flute", "fodder", "fondler", "fountain", "fossil", "funeral", "fungus", "general", "gerbil", "gnome", "goblin", "gravy", "gremlin", "heifer", "hamster", "hole", "hound", "houseplant", "index", "jockey", "juggler", "kebab", "knocker", "knuckle", "lantern", "licker", "lip", "lizard", "llama", "lord", "lump", "maggot", "measle", "meatball", "milk", "minister", "miscreant", "monkey", "muffin", "muppet", "nugget", "ornament", "otter", "paste", "pastry", "peasant", "peddler", "philosopher", "picker", "pie", "pincher", "pirate", "plunger", "pole", "pouch", "potato", "pump", "puppet", "pusher", "rancher", "roast", "sack", "sailor", "scraper", "smuggler", "sniffer", "soup", "spitter", "sponge", "squealer", "squeegee", "squeezer", "stain", "stapler", "steward", "strainer", "stroker", "strumpet", "sweater", "swill", "tamer", "toaster", "tool", "tosser", "troll", "trotters", "trout", "trooper", "trough", "trumpet", "vacuum", "vessel", "volcano", "waffle", "wagon", "walrus", "wanker", "wax", "weasel", "wiggler", "wiper", "whiffler", "whistle", "wizard", "womble", "wrecker", "wrinkle", "yak", "zipper"]

var compliment_adjectives = ["adventurous", "affable", "affectionate", "attractive", "beautiful", "brave", "brilliant", "charming", "compassionate", "considerate", "courageous", "courteous", "dapper", "dedicated", "delectable", "diligent", "empathetic", "enthusiastic", "euphoric", "exuberant", "cheerful", "funny", "fun-loving", "generous", "gregarious", "intuitive", "opalescent", "passionate", "perfect", "pleasant", "poetic", "rainbow-infused", "reliable", "sincere", "sophisticated", "stunning", "talented", "thoughtful", "trustful", "vivacious", "witty"];

var compliment_modifiers = ["alluring", "beaming", "becoming", "blossoming", "captivating", "caring", "chestnut-haired", "dazzling", "doe-eyed", "enchanting", "glowing", "loving", "noble", "powerful", "sassy",  "space", "tropical", "wide-eyed"];

var compliment_nouns = ["fish", "gazelle", "genius", "goddess", "land-mermaid", "mannequin come to life", "minx", "moth", "newborn baby", "otter", "sunfish", "sunflower", "unicorn"];


